# Generated by Django 5.0.4 on 2024-05-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
